### ISSUE TITLE
Weird rebuilding with @opam-alpha/ocaml

### ISSUE THREAD

**Issue by jordwalke** [esy/esy-install#3]
Sorry, I don't have a better place for this - this may not be an issue with `esy` but I'm not sure. I'll update this as I go.

Inside of `ReasonNativeProject` I accidentally did `npm install esy` instead of `npm install -g esy`, which installed `esy` into the local project. This somehow triggered the following build steps:

```sh
hostname:ReasonNativeProject jwalke$ npm install esy

> ocaml@4.2.3 postinstall /Users/jwalke/github/ReasonNativeProject/node_modules/@opam-alpha/ocaml/node_modules/ocaml
> ./yarn-install-project.sh
Configuring the OCaml compiler to use the CC environment variable
which is currently set to () - and defaults to gcc.
++ pwd
+ ./configure -cc '' -no-cfi -prefix /Users/jwalke/github/ReasonNativeProject/node_modules/@opam-alpha/ocaml/node_modules/ocaml
Configuring for host x86_64-apple-darwin16.7.0 ...
Configuring for target x86_64-apple-darwin16.7.0 ...
Using compiler gcc.
```

And then proceeded to recompile ocaml compiler entirely from scratch. I know what that is - it's nothing we're doing in `esy` - it's some really old stuff that we used to experiment with that's getting pulled in. I don't know how they're getting pulled in.
We have an *actual* npm scope called `@opam-alpha` (not the synthesized one we create at runtime in `esy`), which has a ton of old packages that compile themselves in `postinstall`.

Nothing in that `npm` hosted scope should ever be valid or used going forward - it's dead, and useless. Here's how that `@opam-alpha/ocaml` is getting pulled in in my (local) `esy` version of `ReasonNativeProject`: (see ` @opam-alpha/ocaml@4.2.3`).

It looks like jbuilder depends on a version of ocamlfind which might not exist for `esy`, so perhaps it  pulls in the npm hosted`@opam-alpha` `ocamlfind`?

```
├── @opam-alpha/conf-which@1.0.0 extraneous
├─┬ @opam-alpha/jbuilder@1.0.0-beta14
│ ├─┬ @opam-alpha/ocamlfind@1.6.2
│ │ └─┬ ocamlfind-actual@1.6.2 (git+https://github.com/npm-opam/ocamlfind.git#f6ea48c7628210d477ead863d32feba2357b9afe)
│ │   ├─┬ @opam-alpha/conf-m4@1.0.0
│ │   │ ├── opam-installer-bin@0.0.0 (git://github.com/esy-ocaml/opam-installer-bin.git#37d5d7951cc5befd1f124e1abe14b39ba1bdf5a6)
│ │   │ └── substs@0.0.1 (git://github.com/esy-ocaml/substs.git#58b2f5fafbd675665a5a46ef3d142e8e505d2042)
│ │   ├─┬ @opam-alpha/ocaml@4.2.3
│ │   │ └── ocaml@4.2.3 (git+https://github.com/npm-opam/ocaml.git#0bb98be8e5233a02282ed8de0c8965677ddbde33)
│ │   ├─┬ dependency-env@0.1.1
│ │   │ └─┬ resolve@1.4.0
│ │   │   └── path-parse@1.0.5
│ │   └── nopam@0.1.0
│ ├── opam-installer-bin@0.0.0 (git://github.com/esy-ocaml/opam-installer-bin.git#37d5d7951cc5befd1f124e1abe14b39ba1bdf5a6)
│ └── substs@0.0.1 (git://github.com/esy-ocaml/substs.git#58b2f5fafbd675665a5a46ef3d142e8e505d2042)
├── @opam-alpha/ounit@2.0.6 extraneous
```

One fix could be just switching the dynamically inferred scope from "@opam-alpha" to "@opam".

**Comment by jordwalke** [comment]
Oh, I feel pretty foolish. This is totally not `esy`'s fault! I ran an `npm install` command in the project, and it looked at the `package.json` and found `@opam-alpha` packages and did exactly what it's supposed to do - install them from npm.

**Comment by andreypopp** [comment]
I did the same once and also ended up pretty confused. One more reason to
move to `@opam/` prefix.
